name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your needs and implement the best solution.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What use cases does it enable?
      placeholder: This feature would help users to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: detailed-design
    attributes:
      label: Detailed Design (Optional)
      description: If you have a specific implementation in mind, please describe it here.
      placeholder: |
        - API changes:
        - UI changes:
        - Configuration options:
        - Dependencies:

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches could be...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples/Mockups
      description: If applicable, provide examples, mockups, or references to similar implementations.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for adoption
        - Critical - Blocking current work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (Your Assessment)
      description: Based on your understanding, how complex do you think this feature would be to implement?
      options:
        - Simple - Minor changes
        - Medium - Moderate effort
        - Complex - Significant changes
        - Very Complex - Major architectural changes
        - Unknown

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request here.

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that describe the same functionality
          required: true
        - label: I have provided a clear description of the problem and proposed solution
          required: true
        - label: I understand this is a request and not a guarantee of implementation
          required: true